name: Build docs
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          dockerfile: docs/Dockerfile-prod
          path: docs
          username: jamct
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY }}/docs
          registry: docker.pkg.github.com
          tags: latest
