name: Build docs
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          dockerfile: container/Dockerfile
          path: container
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}/mkdocs
          registry: docker.pkg.github.com
          tags: latest
